# Generated by Django 5.1 on 2024-08-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_pacage_booking', '0002_alter_category_options_product_is_sale_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
