# Generated by Django 5.1 on 2024-08-26 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_pacage_booking', '0003_alter_category_options_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category'},
        ),
    ]
