# Generated by Django 5.1 on 2024-09-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_pacage_booking', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
